/**
 * Silver Challenge:
 *  - Persists employees to localStorage as a cache so the app works offline.
 *  - Queues mutations (add / update / delete) when offline and flushes them
 *    the moment the connection is re-established.
 *  - Connects to the backend WebSocket so that employees generated by the
 *    /faker/start loop appear in real time across the whole app.
 */
import { createContext, useContext, useState, useEffect, useCallback, useRef } from 'react'
import { authHeaders } from '../utils/api'

const CACHE_KEY = 'wageora_employees'
const QUEUE_KEY = 'wageora_offline_queue'

const EmployeeContext = createContext(null)

export function EmployeeProvider({ children }) {
  // Seed from localStorage so the app is usable offline on first render
  const [syncVersion, setSyncVersion] = useState(0)
  const [employees, setEmployees] = useState(() => {
    try {
      const cached = localStorage.getItem(CACHE_KEY)
      return cached ? JSON.parse(cached) : []
    } catch { return [] }
  })
  const [isOnline, setIsOnline] = useState(navigator.onLine)
  const wsRef = useRef(null)

  // Keep the localStorage cache in sync with state
  useEffect(() => {
    try { localStorage.setItem(CACHE_KEY, JSON.stringify(employees)) } catch {}
  }, [employees])

  // Track network status
  useEffect(() => {
    const up   = () => setIsOnline(true)
    const down = () => setIsOnline(false)
    window.addEventListener('online',  up)
    window.addEventListener('offline', down)
    return () => {
      window.removeEventListener('online',  up)
      window.removeEventListener('offline', down)
    }
  }, [])

  // ── Offline queue helpers ────────────────────────────────────────────────

  const enqueue = useCallback((op) => {
    try {
      const q = JSON.parse(localStorage.getItem(QUEUE_KEY) || '[]')
      q.push(op)
      localStorage.setItem(QUEUE_KEY, JSON.stringify(q))
    } catch {}
  }, [])

  const flushQueue = useCallback(async () => {
    try {
      const q = JSON.parse(localStorage.getItem(QUEUE_KEY) || '[]')
      if (!q.length) return
      const remaining = []
      for (const op of q) {
        try {
          if (op.type === 'add') {
            const res = await fetch('/api/employees', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json', ...authHeaders() },
              body: JSON.stringify(op.data),
            })
            if (res.ok) {
              const real = await res.json()
              // Replace the temporary placeholder with the real server record
              setEmployees(prev => prev.map(e => e.id === op.tempId ? real : e))
            } else {
              remaining.push(op)
            }
          } else if (op.type === 'update') {
            const res = await fetch(`/api/employees/${op.id}`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json', ...authHeaders() },
              body: JSON.stringify(op.data),
            })
            if (res.ok) {
              const u = await res.json()
              setEmployees(prev => prev.map(e => e.id === op.id ? u : e))
            } else {
              remaining.push(op)
            }
          } else if (op.type === 'delete') {
            const res = await fetch(`/api/employees/${op.id}`, { method: 'DELETE', headers: authHeaders() })
            if (!res.ok) remaining.push(op)
          }
        } catch {
          remaining.push(op)
        }
      }
      localStorage.setItem(QUEUE_KEY, JSON.stringify(remaining))
    } catch {}
  }, [])

  // ── Fetch all employees from the server ──────────────────────────────────

  const fetchAll = useCallback(async () => {
    try {
      const res = await fetch('/api/employees?page_size=100', { headers: authHeaders() })
      if (!res.ok) return
      const data = await res.json()
      setEmployees(data.items)
    } catch {
      // Network is down - the cached state from localStorage remains in use
    }
  }, [])

  // On mount: load fresh data
  useEffect(() => { fetchAll() }, [fetchAll])

  // When coming back online: flush the pending queue, then refresh
  useEffect(() => {
    if (isOnline) {
      flushQueue().then(() => {
        setSyncVersion(v => v + 1)  // signal to EmployeesPage that sync is done
        return fetchAll()
      })
    }
  }, [isOnline, flushQueue, fetchAll])

  // ── WebSocket (Silver: real-time faker updates) ──────────────────────────

  useEffect(() => {
    let ws
    const connect = () => {
      const backendUrl = import.meta.env.VITE_BACKEND_URL
      const wsBase = backendUrl
        ? backendUrl.replace(/^http/, 'ws')
        : `${window.location.protocol === 'https:' ? 'wss:' : 'ws:'}//${window.location.host}`
      ws = new WebSocket(`${wsBase}/api/ws`)
      wsRef.current = ws

      ws.onmessage = (e) => {
        try {
          const msg = JSON.parse(e.data)
          if (msg.event === 'new_employees') {
            setEmployees(prev => {
              const existing = new Set(prev.map(e => e.id))
              const fresh = msg.employees.filter(e => !existing.has(e.id))
              return fresh.length ? [...prev, ...fresh] : prev
            })
          }
        } catch {}
      }

      ws.onclose  = () => setTimeout(connect, 3_000)  // auto-reconnect
      ws.onerror  = () => ws.close()
    }
    connect()
    return () => { wsRef.current?.close() }
  }, [])

  // ── CRUD operations ──────────────────────────────────────────────────────

  const addEmployee = async (data) => {
    if (!isOnline) {
      // Optimistic: insert a temporary record marked with _offline so the UI
      // can show a "pending sync" indicator.
      const tempId = `TEMP_${crypto.randomUUID()}`
      const temp = { id: tempId, ...data, monthlyPay: 0, _offline: true }
      setEmployees(prev => [...prev, temp])
      enqueue({ type: 'add', tempId, data })
      return temp
    }
    const res = await fetch('/api/employees', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...authHeaders() },
      body: JSON.stringify(data),
    })
    if (!res.ok) return null
    const emp = await res.json()
    setEmployees(prev => [...prev, emp])
    return emp
  }

  const updateEmployee = async (id, data) => {
    if (!isOnline) {
      setEmployees(prev =>
        prev.map(e => e.id === id ? { ...e, ...data, _offline: true } : e)
      )
      enqueue({ type: 'update', id, data })
      return
    }
    const res = await fetch(`/api/employees/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...authHeaders() },
      body: JSON.stringify(data),
    })
    if (!res.ok) return
    const updated = await res.json()
    setEmployees(prev => prev.map(e => e.id === id ? updated : e))
  }

  const deleteEmployee = async (id) => {
    if (!isOnline) {
      setEmployees(prev => prev.filter(e => e.id !== id))
      enqueue({ type: 'delete', id })
      return
    }
    const res = await fetch(`/api/employees/${id}`, { method: 'DELETE', headers: authHeaders() })
    if (res.ok) setEmployees(prev => prev.filter(e => e.id !== id))
  }

  const getEmployee = (id) => employees.find(e => e.id === id)

  return (
    <EmployeeContext.Provider
      value={{ employees, addEmployee, updateEmployee, deleteEmployee, getEmployee, isOnline, syncVersion }}
    >
      {children}
    </EmployeeContext.Provider>
  )
}

export const useEmployees = () => useContext(EmployeeContext)